### ISSUE TITLE
Errore PDND nella richiesta di access_token per fruire di e-service ANPR

### ISSUE THREAD

**Issue by rnapoli1983** [pagopa/interop-be-api-gateway#115]
Buonasera,

in ambiente di demo PDND stiamo ricevendo errore nella richiesta di access_token per fruire dei servizi ANPR:

_**Connessione terminata con errore (codice trasporto: 400): {"errors":[{"code":"015-0008","detail":"Unable to generate a token for the given request"}],"status":400,"title":"The request contains bad syntax or cannot be fulfilled.","type":"about:blank"}**_

Di seguito i paramatri inviati in richiesta:

**_client_assertion_**

eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IlBMVWNBbUhyYjg4U0plMGlXdkl3cnJmWGQ5aE1QdnJJZmFNNHVEM1RXOWMifQ.eyJpc3MiOiI1ZjRmMjM3Yy0xMTgyLTRhZWItYmVjMC0zMGVkNWZlZWRjZDciLCJjbGllbnRfaWQiOiI1ZjRmMjM3Yy0xMTgyLTRhZWItYmVjMC0zMGVkNWZlZWRjZDciLCJzdWIiOiI1ZjRmMjM3Yy0xMTgyLTRhZWItYmVjMC0zMGVkNWZlZWRjZDciLCJhdWQiOiJ0ZXN0LmludGVyb3AucGFnb3BhLml0L2NsaWVudC1hc3NlcnRpb24iLCJpYXQiOjE2NjU1ODE3NTIsIm5iZiI6MTY2NTU4MTc1MiwiZXhwIjoxNjY1NTgxODUyLCJqdGkiOiJjYTYzMDMwMi00YTMyLTExZWQtODIxNi0wMDUwNTZhZTRhNDciLCJwdXJwb3NlSWQiOiI0MDQyZjE0OC05ZWVmLTRkOTgtODc1OC1mYTUwZjlhZjUyMDUifQ.B5xy1p66CV-YdCG0flVbTErim-zrj9xyN_InG8C-6WyFiF10oeutHq80bpKX78jALQ8YsEybB8IFP0SihiCNWUmH1kP-fWl-roL_eIXoO9sB9ECE0YVmsbX98bNM9twRrI5BG_qUqLvcS09GtLHS9fi1CCr0lVp0tDxLgHJROhxACR361Wq-CpwjosZ7Dzy2iBcftNaXu1_xjpJ_SJk5K7mInIIkK9WTRYXXQRyfoI7X9sjPQ-2ot6tqbb6LW0t4_6mbXr1F79tVBGLvWN6BMMPW3Bj4ERcPcESHBwR0ecW_QbicndrrhwoV-JbRkXmkTsHIIidDp2KILPdB3v-kMA

header:
{
  "alg": "RS256",
  "typ": "JWT",
  "kid": "PLUcAmHrb88SJe0iWvIwrrfXd9hMPvrIfaM4uD3TW9c"
}
payload:
{
  "iss": "5f4f237c-1182-4aeb-bec0-30ed5feedcd7",
  "client_id": "5f4f237c-1182-4aeb-bec0-30ed5feedcd7",
  "sub": "5f4f237c-1182-4aeb-bec0-30ed5feedcd7",
  "aud": "test.interop.pagopa.it/client-assertion",
  "iat": 1665581752,
  "nbf": 1665581752,
  "exp": 1665581852,
  "jti": "ca630302-4a32-11ed-8216-005056ae4a47",
  "purposeId": "4042f148-9eef-4d98-8758-fa50f9af5205"
}

**_client_id_**

5f4f237c-1182-4aeb-bec0-30ed5feedcd7

Potreste aiutarci ?

Buona giornata.

Grazie mille.

Roberto Napoli

**Comment by rnapoli1983** [comment]
Dopo vostro intervento il problema si è risolto.

Grazie mille per il supporto

**Comment by marcocipri** [comment]
l'ambiente di Demo è stato ristabilito
