### ISSUE TITLE
attributes by agreement

### ISSUE THREAD

**Issue by amollicone1982** [pagopa/interop-be-api-gateway#13]
La chiamata a /agreements/{agreementId}/attributes con 
agreementId = 65328879-c1c3-4ca8-88e8-81aac323a8bd

non ritorna attributi nonostante questi siano stati verificati

**Comment by amollicone1982** [comment]
Continuo a non ricevere gli attributi

**Comment by P3trur0** [comment]
Il gateway aggiornato è stato rilasciato ora in test. Si può riprovare.
