### ISSUE TITLE
Errori bloccanti test PUC-PDND-ANPR

### ISSUE THREAD

**Issue by rnapoli1983** [pagopa/interop-be-api-gateway#38]
Buongiorno sono Roberto Napoli (Sogei),

vi scrivo perchè, stamani nell'eseguire i test inerenti le chiamate dall'orchestratore del PUC agli e-service ANPR su PDND, otteniamo errori bloccanti proprio da PDND che non ci consentono di ottenere access token e quindi completare il flusso.

In particolare l'errore ottenuto è il seguente:

**_"errors":[{"code":"013-0011","detail":"Error while creating a token for this request - JWT audience rejected: [testE002.anpr.interno.it]"}],"status":500,"title":"There was an internal server error.","type":"about:blank"}_**

Ora come pattuito e definito con voi, soprattutto con Marco Cipri, l'audience inerente (testE002.anpr.interno.it) è corretto perchè, come fruitore, stiamo interrogando un e-service di un erogatore, mediante PDND, con un client, definito da noi che rappresenta la nostra applicazione, e quindi l'aud deve coincidere con quello definito dall'erogatore come è.

L'audience "test.interop.pagopa.it" deve essere settato invece quando, mediante un client definito come Interop M2M, si vuole ottenere access token solo per fruire delle API PDND-Interop.

Detto questo quindi, per noi, l'errore ottenuto non è giustificabile dallo scenario di test che abbiamo realizzato e vi chiediamo urgentemente supporto in quanto abbiamo una nostra scadenza imminente, per queste attività di testing, da onorare.

Di seguito vi riporto anche l'assertion e vi allego trace log:

**Assertion**: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IlBMVWNBbUhyYjg4U0plMGlXdkl3cnJmW
GQ5aE1QdnJJZmFNNHVEM1RXOWMifQ.eyJpc3MiOiI1ZjRmMjM3Yy0xMTgyLTRhZWItYmVjMC0zMGVkNWZlZWRjZDciLCJjbGllbnRfaWQiOiI1ZjRmMjM3Yy0xMTgyLTRhZWItYmVjMC0zMGVkNWZlZWRjZDciLCJzdWIiOiI1ZjRmMjM3Yy0xMTgyLTRhZWItYmVjMC0zMGVkNWZlZWRjZDciLCJhdWQiOiJ0ZXN0RTAwMi5hbnByLmludGVybm8uaXQiLCJpYXQiOjE2NDkyNDA0NTAsIm5iZiI6MTY0OTI0MDQ1MCwiZXhwIjoxNjQ5MjQwNTUwLCJqdGkiOiIzYjU2M2QwMi1iNTkzLTExZWMtOWVhYS0wMDUwNTZhZTRhNDciLCJwdXJwb3NlSWQiOiI0MDQyZjE0OC05ZWVmLTRkOTgtODc1OC1mYTUwZjlhZjUyMDUifQ.S9b36qFmI0imI2D4ge3YnhbiJZxWae1nRb84FnWM9COCqgbTB0rhQHcjy0XVxMLR7apYVbGJ0RKmNGPMppg8BOyS3Ih_1-3XlRmLbDS8NudkyC8F2vNKgn5GrtkbkI5mROtawPgIALqJCsW7joLIGqP8sFrj4Zrr17PVf2NKJvbNET6U9TO1mJGGDavxf90kbSXZ9dH9S2p5IK8-oLj1Yj9U2CnDxO-CVe1Ip2GKaodZ_1hs5yhttbPQnMR7cq11Lr1za3CkllpdHXAplDCzcxbpMqEWlcnarnSWF2doOAE7eqkepnotvEiWt9JOX3NjG7lylD5KYjUM-BcV8VFBeg&client_id=5f4f237c-1182-4aeb-bec0-30ed5feedcd7

Decodificata ha il seguente **header**:
{
  "alg": "RS256",
  "typ": "JWT",
  "kid": "PLUcAmHrb88SJe0iWvIwrrfXd9hMPvrIfaM4uD3TW9c"
}
ed il seguente **payload**:
{
  "iss": "5f4f237c-1182-4aeb-bec0-30ed5feedcd7",
  "client_id": "5f4f237c-1182-4aeb-bec0-30ed5feedcd7",
  "sub": "5f4f237c-1182-4aeb-bec0-30ed5feedcd7",
  "aud": "testE002.anpr.interno.it",
  "iat": 1649240450,
  "nbf": 1649240450,
  "exp": 1649240550,
  "jti": "3b563d02-b593-11ec-9eaa-005056ae4a47",
  "purposeId": "4042f148-9eef-4d98-8758-fa50f9af5205"
}

Attendo un vostro riscontro.

Grazie mille.

Buona giornata.

Roberto Napoli

[trace_log.txt](https://github.com/pagopa/interop-be-api-gateway/files/8426575/trace_log.txt)

**Comment by marcocipri** [comment]
Buonasera,
credo ci sia un po di confusione con il bug relativo al FE in cui erroneamente venivano invertite le audience a cui fai riferimento

https://github.com/pagopa/pdnd-interop-frontend/issues/48

In quel contesto l'errore c'era perchè l'audience della richiesta non era coerente con chi erogava il servizio.
**Invece** nell'esempio che citi, il destinatario della richiesta non è l'erogatore ma la piattaforma di Interoperabilità coerentente con la RFC

https://datatracker.ietf.org/doc/html/rfc7521

in cui si dichiara : 

Audience
      A value that identifies the party or parties intended to process
      the assertion.  The URL of the token endpoint, as defined in
      Section 3.2 of OAuth 2.0 [RFC6749], can be used to indicate that
      the authorization server is a valid intended audience of the
      assertion.
      
    
in altre parole, l'asserzione deve essere processata dalla piattaforma di interoperabilità.

**Comment by rnapoli1983** [comment]
Mi spiace ma la confusione nasce dal fatto che ogni volta ridefinite scenari diversi precedentemente concordati

**Comment by ioggstream** [comment]
@rnapoli1983 nell'`aud` va il destinatario del token/asserzione. Se il destinatario è PDND, va messo l'URL del Token Endpoint, se è l'Erogatore, va messo l'URL dell'erogatore.

**Comment by rnapoli1983** [comment]
Abbiamo fatto un test e dopo aver modificato l'audience la negoziazione del token avviene con successo.

Di seguito riporto l'access token ritornato

INFO <06-04-2022 15:50:37> <id:89746234-b5b0-11ec-9eaa-005056ae4a47> Messaggio ricevuto (ContentType:application/json) :
{"access_token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsInVzZSI6InNpZyIsImtpZCI6IlJPc3B6RDBaMWwzUzZRcGR5SmpiRzNKV21jT2x2YWZndlNnM001UEtxd0EifQ.eyJhdWQiOiJ0ZXN0RTAwMi5hbnByLmludGVybm8uaXQiLCJzdWIiOiI1ZjRmM
jM3Yy0xMTgyLTRhZWItYmVjMC0zMGVkNWZlZWRjZDciLCJuYmYiOjE2NDkyNTMwMzcsImlzcyI6ImY1N2U2ZDQwLTE4NjQtNGNlNy1iMjNlLWYwYzE3OGMzZTFmMyIsInR5cCI6ImF0K2p3dCIsImV4cCI6MTY0OTI1MzA1NywiaWF0IjoxNjQ5MjUzMDM3LCJjbGllbn
RfaWQiOiI1ZjRmMjM3Yy0xMTgyLTRhZWItYmVjMC0zMGVkNWZlZWRjZDciLCJqdGkiOiI3ZGU1NGQzYS05ZGRmLTQ2YmItYThkMC04MmU0ZDBkZGExZDMifQ.Dz7z3rkv8U4NAhbw0LzaTlbjZdV-EPvygXUUIxDypNY6Fo45uNCQ3waW-ClpXAW-vfLPK_nkjyI4JZ3j
A86ODYQ-6Av411d94aRDHn1oZagb7a3lHv4hSjVhamcCqN5WQzL0qI09BUQi1oawktpwdz-h4m__xOBYVuLgoTg261r25QIYFK9JRQvOqa-kAgQA2Xq_yeQmgcgUwD3I6Zvg_nDMCtTMBzwhE9bs7cgHyUa7By6Jvb3uYXTKa1wAREd3aD6ql1M54N3Z55wpUzDbp6kQr
_auYIHNgrYqsnanX7hzs8RAnEhTNUAlV4NSWEiED-t3xcElvSnj1icOoy_yCg","expires_in":20,"token_type":"Bearer"}

Decodificando l'access token ho però notato che nel payload che riporto di seguito non è presente il purposeId:

{
  "aud": "testE002.anpr.interno.it",
  "sub": "5f4f237c-1182-4aeb-bec0-30ed5feedcd7",
  "nbf": 1649253037,
  "iss": "f57e6d40-1864-4ce7-b23e-f0c178c3e1f3",
  "typ": "at+jwt",
  "exp": 1649253057,
  "iat": 1649253037,
  "client_id": "5f4f237c-1182-4aeb-bec0-30ed5feedcd7",
  "jti": "7de54d3a-9ddf-46bb-a8d0-82e4d0dda1d3"
}

Se non erro abbiamo detto dovrebbe esserci altrimenti l'erogatore come recupera poi l'accordo ?

Corretto ?

**Comment by beetlecrunch** [comment]
Confermo che al momento il campo non è esposto, stiamo già lavorando per esporlo.

**Comment by ioggstream** [comment]
@beetlecrunch sempre https URL nell'aud pure nella response :)

**Comment by rnapoli1983** [comment]
Buongiorno @ioggstream ,

abbiamo notato anche noi.

In effetti l'aud dovrebbe avere un formato tipo:

**"aud": "https://erogatore.example/anpr/v1"**

Però, per velocizzare la fase di testing che ci vede coinvolti, secondo me al momento, è meglio concentrarsi sull'esposizione del purposeId nel token elaborato da PDND che è fondamentale e bloccante, visto che la sua presenza la davamo per scontata come da specifiche pattuite.

**Comment by beetlecrunch** [comment]
Buongiorno @rnapoli1983,
abbiamo appena rilasciato la modifica per inserire il purposeId nel token.

In attesa di un vostro riscontro.
Grazie

**Comment by rnapoli1983** [comment]
Buongiorno @beetlecrunch facciamo dei test e vi facciamo sapere per l'aud lo facciamo in seguito se siete d'accordo

**Comment by rnapoli1983** [comment]
buongiorno @beetlecrunch,

vi confermiamo che ora appare anche il purposeId:

![image](https://user-images.githubusercontent.com/30468060/162170871-5322026d-a670-4736-899a-f2ca50e42f85.png)

Per l'aud dobbiamo la modifica va concordata prima, perchè ANPR si appresterà, nella gioronata di lunedì e nei giorni successivi, a fare i WAPT di rito propedeutici per la messa in produzione e quindi gli ambienti dovranno essere funzionanti e ibernati.

Vero @amollicone 1982 ?

**Comment by amollicone1982** [comment]
Confermo quanto detto da Roberto. La modifica dll'aud prevediamola per martedi/mercoledi

**Comment by rnapoli1983** [comment]
Buonasera @marcocipri, @beetlecrunch mi sembra doveroso, ringraziandovi del supporto, comunicarvi che abbiamo il flusso PUC-PDND-ANPR:

{
    "datiSoggetto": {
        "generalita": {
            "codiceFiscale": {
                "codFiscale": "DCLVNT58H11H501C",
                "statoCf": "Validato"
            },
            "cognome": "DI CIAULA",
            "nome": "VALENTINO",
            "sesso": "M",
            "dataNascita": "11/06/1958",
            "luogoNascita": {
                "comune": {
                    "nomeComune": "TORINO",
                    "codiceIstat": "001272",
                    "siglaProvinciaIstat": "TO"
                }
            }
        },
        "legameSoggetto": {}
    },
    "componenti": [
        {
            "generalita": {
                "codiceFiscale": {
                    "codFiscale": "DCLVNT58H11H501C",
                    "statoCf": "Validato"
                },
                "cognome": "DI CIAULA",
                "nome": "VALENTINO",
                "sesso": "M",
                "dataNascita": "11/06/1958",
                "luogoNascita": {
                    "comune": {
                        "nomeComune": "TORINO",
                        "codiceIstat": "001272",
                        "siglaProvinciaIstat": "TO"
                    }
                }
            },
            "legameSoggetto": {
                "codiceLegame": "1"
            }
        }
    ]
}

**Comment by ioggstream** [comment]
@rnapoli1983 off topic: ma i nomi dei campi sono quelli storici? Perché non soni allineati con le ontologie agid.

**Comment by rnapoli1983** [comment]
Buonasera @ioggstream non ho capito la domanda ma essendo dati ANPR conviene che la giri a loro.

Buona serata
